version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: ai_chatbot_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - ai_chatbot_db_data:/var/lib/postgresql/data
      -
volumes:
  ai_chatbot_db_data:
